import express from 'express';
import cors from 'cors';
import { spawn } from 'child_process';
import { promises as fs } from 'fs';
import { randomBytes } from 'crypto';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());
app.use(express.json({ limit: '10mb' }));

// Path to the C++ lexer executable (macOS/Linux: 'specula', Windows: 'specula.exe')
const LEXER_EXECUTABLE = path.join(__dirname, '..', 'build', 'specula');

/**
 * Generate a unique temporary filename
 */
function generateTempFilename() {
  const randomId = randomBytes(8).toString('hex');
  return `tmp_${randomId}.txt`;
}

/**
 * Clean up temporary files
 */
async function cleanupFiles(inputFile, outputFile) {
  try {
    await fs.unlink(inputFile).catch(() => {});
    await fs.unlink(outputFile).catch(() => {});
  } catch (error) {
    console.error('Error cleaning up temporary files:', error.message);
  }
}

/**
 * POST /lex
 * Accepts: { code: string }
 * Returns: { file: {...}, errors: [...], tokens: [...] }
 */
app.post('/lex', async (req, res) => {
  const { code } = req.body;

  if (!code || typeof code !== 'string') {
    return res.status(400).json({
      error: 'Missing or invalid "code" field in request body'
    });
  }

  const tempInputFile = path.join(__dirname, generateTempFilename());
  const tempInputBasename = path.basename(tempInputFile, '.txt');
  const tempOutputFile = path.join(__dirname, `${tempInputBasename}_tokens.txt`);

  try {
    // Write input code to temporary file
    await fs.writeFile(tempInputFile, code, 'utf-8');

    // Execute the C++ lexer
    const lexerProcess = spawn(LEXER_EXECUTABLE, [tempInputFile], {
      cwd: __dirname,
      windowsHide: true
    });

    let stderr = '';
    let responseSent = false;

    lexerProcess.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    lexerProcess.on('error', async (error) => {
      if (responseSent) return;
      responseSent = true;
      await cleanupFiles(tempInputFile, tempOutputFile);
      return res.status(500).json({
        error: `Failed to execute lexer: ${error.message}`
      });
    });

    lexerProcess.on('close', async (code) => {
      if (responseSent) return;
      try {
        if (code !== 0 && code !== null) {
          console.error(`Lexer process exited with code ${code}`);
          console.error(`stderr: ${stderr}`);
        }

        // Read the output file generated by the lexer
        const outputData = await fs.readFile(tempOutputFile, 'utf-8');
        const result = JSON.parse(outputData);

        // Clean up temporary files
        await cleanupFiles(tempInputFile, tempOutputFile);

        // Return the lexer output
        responseSent = true;
        res.json(result);
      } catch (error) {
        if (responseSent) return;
        responseSent = true;
        await cleanupFiles(tempInputFile, tempOutputFile);
        
        if (error.code === 'ENOENT') {
          return res.status(500).json({
            error: 'Lexer did not generate output file. The lexer may have encountered an error.'
          });
        }

        return res.status(500).json({
          error: `Failed to read lexer output: ${error.message}`
        });
      }
    });
  } catch (error) {
    await cleanupFiles(tempInputFile, tempOutputFile);
    return res.status(500).json({
      error: `Server error: ${error.message}`
    });
  }
});

// Parser API URL (C# backend)
const PARSER_API_URL = process.env.PARSER_API_URL || 'http://localhost:5000/api/analyze';

/**
 * POST /parse
 * Proxy to the C# syntax analyzer backend
 * Accepts: { file: {...}, errors: [...], tokens: [...] }
 * Returns: Parser output JSON
 */
app.post('/parse', async (req, res) => {
  try {
    const response = await fetch(PARSER_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(req.body),
    });

    if (!response.ok) {
      const errorText = await response.text();
      return res.status(response.status).json({
        error: `Parser API error: ${errorText}`
      });
    }

    const result = await response.json();
    res.json(result);
  } catch (error) {
    console.error('Parser proxy error:', error.message);
    return res.status(500).json({
      error: `Failed to connect to parser: ${error.message}`
    });
  }
});

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({ status: 'ok', message: 'Lexer API is running' });
});

app.listen(PORT, () => {
  console.log(`Lexer API server running on http://localhost:${PORT}`);
  console.log(`Lexer executable: ${LEXER_EXECUTABLE}`);
  console.log(`Parser API URL: ${PARSER_API_URL}`);
});
