#include "Tokens.hpp"

const std::unordered_map<TokenType, std::string, TokenTypeHash> tokenTypeToString = {
    { TokenType::L_INT, "L_INT" },
    { TokenType::L_FLOAT, "L_FLOAT" },
    { TokenType::L_DOUBLE, "L_DOUBLE" },
    { TokenType::L_CHAR, "L_CHAR" },
    { TokenType::L_STRING, "L_STRING" },
    { TokenType::L_BOOL, "L_BOOL" },
    { TokenType::L_NULL, "L_NULL" },

    { TokenType::K_LET, "K_LET" },
    { TokenType::K_TYPE, "K_TYPE" },

    { TokenType::K_IF, "K_IF" },
    { TokenType::K_ELSE, "K_ELSE" },

    { TokenType::K_FOR, "K_FOR" },
    { TokenType::K_WHILE, "K_WHILE" },
    { TokenType::K_DO, "K_DO" },
    { TokenType::K_IN, "K_IN" },
    { TokenType::K_BREAK, "K_BREAK" },

    { TokenType::K_RET, "K_RET" },
    { TokenType::K_FN, "K_FN" },

    { TokenType::K_STRUCT, "K_STRUCT" },
    { TokenType::K_INTERFACE, "K_INTERFACE" },
    { TokenType::K_IMPL, "K_IMPL" },
    { TokenType::K_SELF, "K_SELF" },
    { TokenType::K_THIS, "K_THIS" },

    { TokenType::K_IMPORT, "K_IMPORT" },
    { TokenType::K_EXPORT, "K_EXPORT" },
    { TokenType::K_EXPORT_DEFAULT, "K_EXPORT_DEFAULT" },

    { TokenType::K_CONTRACT, "K_CONTRACT" },
    { TokenType::K_LISTENER, "K_LISTENER" },
    { TokenType::K_STATE, "K_STATE" },
    { TokenType::K_INIT_STATE, "K_INIT_STATE" },
    { TokenType::K_FAIL, "K_FAIL" },
    { TokenType::K_AUTO_RESET, "K_AUTO_RESET" },
    { TokenType::K_AUTO_MOVE, "K_AUTO_MOVE" },
    { TokenType::K_ROLES, "K_ROLES" },
    { TokenType::K_RESPOND, "K_RESPOND" },
    { TokenType::K_ON, "K_ON" },
    { TokenType::K_LISTEN, "K_LISTEN" },
    { TokenType::K_TARGET, "K_TARGET" },
    { TokenType::K_AS, "K_AS" },
    { TokenType::K_USING, "K_USING" },
    { TokenType::K_AFTER, "K_AFTER" },
    { TokenType::K_BEFORE, "K_BEFORE" },

    { TokenType::K_OWN, "K_OWN" },
    { TokenType::K_MOVE, "K_MOVE" },
    { TokenType::K_SHARED, "K_SHARED" },
    { TokenType::K_VIEW, "K_VIEW" },
    { TokenType::K_OWN, "K_OWN" },
    { TokenType::K_SHARE, "K_SHARE" },
    { TokenType::K_REF, "K_REF" },
    { TokenType::K_MUT, "K_MUT" },
    { TokenType::K_CONST, "K_CONST" },
    { TokenType::K_THR_LOCAL, "K_THR_LOCAL" },
    { TokenType::K_SYNC, "K_SYNC" },
    { TokenType::K_INFER, "K_INFER" },
    { TokenType::K_NETWORK, "K_NETWORK" },

    { TokenType::K_ASYNC, "K_ASYNC" },
    { TokenType::K_AWAIT, "K_AWAIT" },
    { TokenType::K_THREAD, "K_THREAD" },
    { TokenType::K_SPAWN, "K_SPAWN" },

    { TokenType::OP_EQUALS, "OP_EQUALS" },
    { TokenType::OP_PLUS, "OP_PLUS" },
    { TokenType::OP_MINUS, "OP_MINUS" },
    { TokenType::OP_MULT, "OP_MULT" },
    { TokenType::OP_DIVIDE, "OP_DIVIDE" },
    { TokenType::OP_MOD, "OP_MOD" },
    { TokenType::OP_PERIOD, "OP_PERIOD" },

    { TokenType::OP_REL_EQ, "OP_REL_EQ" },
    { TokenType::OP_REL_NOT_EQ, "OP_REL_NOT_EQ" },
    { TokenType::OP_REL_LESS, "OP_REL_LESS" },
    { TokenType::OP_REL_GREATER, "OP_REL_GREATER" },
    { TokenType::OP_REL_LESS_EQ, "OP_REL_LESS_EQ" },
    { TokenType::OP_REL_GREATER_EQ, "OP_REL_GREATER_EQ" },
    { TokenType::OP_PLUS_EQ, "OP_PLUS_EQ" },
    { TokenType::OP_MINUS_EQ, "OP_MINUS_EQ" },
    { TokenType::OP_MULT_EQ, "OP_MULT_EQ" },
    { TokenType::OP_DIV_EQ, "OP_DIV_EQ" },
    { TokenType::OP_MOD_EQ, "OP_MOD_EQ" },


    { TokenType::OP_LEFT_OP, "OP_LEFT_OP" },
    { TokenType::OP_RIGHT_OP, "OP_RIGHT_OP" },
    { TokenType::OP_BIDIR_OP, "OP_BIDIR_OP" },

    { TokenType::OP_AND, "OP_AND" },
    { TokenType::OP_OR, "OP_OR" },
    { TokenType::OP_NOT, "OP_NOT" },
    { TokenType::OP_BITW_AND, "OP_BITW_AND" },
    { TokenType::OP_BITW_OR, "OP_BITW_OR" },
    { TokenType::OP_BITW_XOR, "OP_BITW_XOR" },
    { TokenType::OP_SHIFT_L, "OP_SHIFT_L" },
    { TokenType::OP_SHIFT_R, "OP_SHIFT_R" },

    { TokenType::OP_INCR, "OP_INCR" },
    { TokenType::OP_DECR, "OP_DECR" },

    { TokenType::D_PAR_OP, "D_PAR_OP" },
    { TokenType::D_PAR_CLO, "D_PAR_CLO" },
    { TokenType::D_BRAC_OP, "D_BRAC_OP" },
    { TokenType::D_BRAC_CLO, "D_BRAC_CLO" },
    { TokenType::D_CBRAC_OP, "D_CBRAC_OP" },
    { TokenType::D_CBRAC_CLO, "D_CBRAC_CLO" },

    { TokenType::D_COLON, "D_COLON" },
    { TokenType::D_SEMICOLON, "D_SEMICOLON" },
    { TokenType::IDENT, "IDENT" },

    { TokenType::NEW_LINE, "NEW_LINE" },
    { TokenType::SPACE, "SPACE" },
    { TokenType::UNKNOWN, "UNKNOWN" },
    { TokenType::TAB, "TAB" },
    { TokenType::COMMA, "COMMA" },
    { TokenType::AT_SYMBOL, "AT_SYMBOL" }
};
